version: '3.8'

services:
  # Baza podataka na koju se engine oslanja
  db:
    image: postgres:15
    container_name: anonify_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anonify_db
    ports:
      - "5433:5432"

  # Batch/Script servis
  app:
    build: .
    container_name: anonify_app
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
    depends_on:
      - db

  # Streamlit Web UI
  ui:
    build: .
    container_name: anonify_ui
    command: streamlit run app_ui.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - db